config/routes.rb
Rails.application.routes.draw do
  root 'ceaps#index'
  get 'expenses' => 'expenses#index'
  get 'expenses/show' => 'expenses#show'
  resources :ceaps
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ceap.rb
class Ceap < ApplicationRecord
  has_many :deputies
end

app/models/deputy.rb
class Deputy < ApplicationRecord
  belongs_to :ceap
  has_many :expenses

  def higher_expense
    expenses.sort_by(&:value).reverse.first
  end
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :deputy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ceaps_controller.rb
class CeapsController < ApplicationController
  before_action :set_ceap, only: %i[ show ]

  # GET /ceaps or /ceaps.json
  def index
    @ceaps = Ceap.all
  end

  # GET /ceaps/1 or /ceaps/1.json
  def show
    @deputies =  @ceap.deputies
  end

  # GET /ceaps/new
  def new
    @ceap = Ceap.new
  end
  # GET /ceaps/1/edit

  # POST /ceaps or /ceaps.json
  def create
    @ceap = Ceap.new(ceap_params)
    @ceap.save(validate: false)
    file = params[:file].tempfile.path
    ReadCsvJob.perform_later(file, @ceap)

    respond_to do |format|
      if @ceap.save
        format.html { redirect_to '/', notice: "Seu Arquivo está sendo extraido. Pode levar um tempo. Aguarde!!" }
        format.json { render :show, status: :created, location: @ceap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ceap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ceaps/1 or /ceaps/1.json
  def destroy
    @ceap = Ceap.find(params[:id])
    DestroyCeapJob.perform_later(@ceap)
    respond_to do |format|
      format.html { redirect_to ceaps_url, notice: "Ceap Sendo Deletado" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ceap
      @ceap = Ceap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ceap_params
      params.require(:ceap).permit(:name, :email, :total_spend)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expenses, only: %i[ index ]
  before_action :set_expense, only: %i[ show ]

  def index
  end

  def show
  end
  private

  def set_expenses
    # @ceap = Ceap.find(params[:ceap_id])
    @deputy =  Deputy.where(id: params[:id]).first
    @expenses = @deputy.expenses
    @higher_expense = @deputy.higher_expense
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ceaps_helper.rb
module CeapsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def details(expense)
    "#{expenses_show_path}?id=#{expense.id}"
  end
end

app/views/ceaps/_form.html.erb
<%= form_with(model: ceap, multipart: true) do |form| %>
  <% if ceap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ceap.errors.count, "error") %> prohibited this ceap from being saved:</h2>

      <ul>
        <% ceap.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", required: true%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", required: true%>
  </div>

  
  <div class="input-group mb-3">
    <label class="input-group-text" for="inputGroupFile01">Arquivo CSV</label>
    <%= file_field_tag :file, class:"form-control"%>
  </div>

  <div class="actions">
    <%= form.submit "Criar Ceap", class: "btn btn-info" %>
  </div>
<% end %>

app/views/ceaps/edit.html.erb
<h1>Editing Ceap</h1>

<%= render 'form', ceap: @ceap %>

<%= link_to 'Show', @ceap %> |
<%= link_to 'Back', ceaps_path %>

app/views/ceaps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ceaps</h1>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Valor Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @ceaps.each do |ceap| %>
      <tr scope="col">
        <td><%= ceap.name %></td>
        <td><%= ceap.email %></td>
        <td><%= number_to_currency(ceap.total_spend, unit: "R$", separator: ",", delimiter: ".") %></td>
        <td><%= link_to 'Deputados', ceap, class: "btn btn-info"%></td>
        <td><%= link_to 'Excluir', ceap,  class: "btn btn-info", method: :delete, data: { confirm: 'Quer mesmo excluir?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="col-xs-12 align-right">
  <%= link_to 'New Ceap', new_ceap_path, class: "btn btn-success bg-green waves-effect" %>
</div>

app/views/ceaps/new.html.erb
<h1>Novo Ceap</h1>

<%= render 'form', ceap: @ceap %>

<%= link_to 'Back', ceaps_path, class: "btn btn-info" %>

app/views/ceaps/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Documento</th>
      <th>Estado</th>
      <th>Maior Despesa </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @deputies.each do |deputy| %>
      <tr scope="col">
        <td><%= deputy.name %></td>
        <td><%= deputy.document %></td>
        <td><%= deputy.state %></td>
        <td><%= deputy.higher_expense.value %></td>
        <td><a href=<%="/expenses?ceap_id=#{@ceap.id}&id=#{deputy.id}"%> class="btn btn-info">Despesas</a></td></tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', ceaps_path, class: "btn btn-info"%>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Despesas do Deputado: <%= @deputy.name %></h1>
<img src="<%= @deputy.photo %>" alt="<%= @deputy.name %>" class="img-thumbnail">

<table class="table table-dark">
  <thead>
    <tr>
      <th>Estabelecimento</th>
      <th>Data</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%total = 0%>
  <tbody >
    <% @expenses.each do |expense| %>
      <tr scope="col">
        <td><%= expense.establishment %></td>
        <td><%= expense.date %></td>
        <td><%= number_to_currency(expense.value, unit: "R$", separator: ",", delimiter: ".") %> </td>
        <% total += expense.value %>
        <td><%= link_to 'Detalhes', details(expense)	, class: "btn btn-info"%></td>

      </tr>
    <% end %>
  <tr scope="col"> <td colspan="3"><strong> Maior Despesa </strong></td></tr>
  <tr scope="col">
    <td><%= @higher_expense.establishment %></td>
    <td><%= @higher_expense.date %></td>
    <td><%= number_to_currency(@higher_expense.value, unit: "R$", separator: ",", delimiter: ".") %> </td>
    <% total += @higher_expense.value %>
    <td><%= link_to 'Detalhes', details(@higher_expense)	, class: "btn btn-info"%></td>
  </tr>
  </tbody>

</table>



<hr class="border-line">
  <small>Valor Total:</small>
  <p class="m-0 text-primary">
    <h3 class="text-primary text-danger"><b><%= number_to_currency(total, unit: "R$", separator: ",", delimiter: ".") %></b></h3>
  </p>
<hr class="border-line">

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">

  <p>
    <strong>Fornecedor:</strong>
    <%= @expense.establishment %>
  </p>
    <p>
    <strong>CNPJ/CPF:</strong>
    <%= @expense.document %>
  </p>

  <p>
    <strong>Numero:</strong>
    <%= @expense.phone %>
  </p>

  <p>
    <strong>Data da Emissao:</strong>
    <%= @expense.date.to_date %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= number_to_currency(@expense.value, unit: "R$", separator: ",", delimiter: ".") %>
  </p>

  <% if @expense.note.present? %>
    <p>
      <strong>Link Documento:</strong>
      <a target="_blank" href="<%= @expense.note %>">PDF</a>
    </p>
  <% end %>
</div>

<%= link_to 'Voltar', '/', class: "btn btn-info"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Congressperson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>